### ISSUE TITLE
win10下提示出错

### ISSUE THREAD

**Issue by yardian** [s7ckTeam/sWebScanner#2]
[15:19:33] [INFO] 获取api
[15:19:33] [INFO] 获取api完成
Traceback (most recent call last):
  File "sWebScanner.py", line 13, in <module>
    console.main()
  File "E:\123\Scan\sWebScanner-main\console.py", line 110, in main
    asy_main(*args)
  File "E:\123\Scan\sWebScanner-main\script\probe_val.py", line 111, in asy_main
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())  # 加上这一行处理代理，不能放在协程函数内
AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'

**Comment by luwenhao0326** [comment]
> [15:19:33] [INFO] 获取api
> [15:19:33] [INFO] 获取api完成
> Traceback (most recent call last):
> File "sWebScanner.py", line 13, in
> console.main()
> File "E:\123\Scan\sWebScanner-main\console.py", line 110, in main
> asy_main(*args)
> File "E:\123\Scan\sWebScanner-main\script\probe_val.py", line 111, in asy_main
> asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy()) # 加上这一行处理代理，不能放在协程函数内
> AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'

python版本兼容问题，需要python版本大于等于3.7，后续会更新解决，先把这行代码注释掉也行
